name: Build binary

on: [push]

jobs:
  build_mac:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Env
      run: |
        env
        pwd
        ls
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/Downloads/source
          ~/Documents/temp/build
        key: ${{ runner.os }}-20210307
    - name: Setup seed
      env:
        AMIKO_GOOGLE_CLIENT_ID: ${{ secrets.AMIKO_GOOGLE_CLIENT_ID }}
        AMIKO_GOOGLE_CLIENT_SECRET: ${{ secrets.AMIKO_GOOGLE_CLIENT_SECRET }}
        COMED_GOOGLE_CLIENT_ID: ${{ secrets.COMED_GOOGLE_CLIENT_ID }}
        COMED_GOOGLE_CLIENT_SECRET: ${{ secrets.COMED_GOOGLE_CLIENT_SECRET }}
      run: |
        cp seed.in.conf seed.conf
        sed -i.bak -e "s/AMIKO_GOOGLE_CLIENT_ID=''/AMIKO_GOOGLE_CLIENT_ID='$AMIKO_GOOGLE_CLIENT_ID'/g" seed.conf
        sed -i.bak -e "s/AMIKO_GOOGLE_CLIENT_SECRET=''/AMIKO_GOOGLE_CLIENT_SECRET='$AMIKO_GOOGLE_CLIENT_SECRET'/g" seed.conf
        sed -i.bak -e "s/COMED_GOOGLE_CLIENT_ID=''/COMED_GOOGLE_CLIENT_ID='$COMED_GOOGLE_CLIENT_ID'/g" seed.conf
        sed -i.bak -e "s/COMED_GOOGLE_CLIENT_SECRET=''/COMED_GOOGLE_CLIENT_SECRET='$COMED_GOOGLE_CLIENT_SECRET'/g" seed.conf
    - name: Setup step
      run: |
        sed -e "s/#STEP/STEP/g" steps.in.conf > steps.conf
    - name: Build
      run: sudo ./build.sh
    - uses: actions/upload-artifact@v2
      with:
        name: Artifact
        path: |
          ~/Documents/temp/build/AmiKo-wx/AmiKo-wx-mk/*.dmg
          ~/Documents/temp/build/AmiKo-wx/AmiKo-wx-mk/*.md5

  build_linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Env
      run: |
        env
        pwd
        ls
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/Downloads/source
          ~/Documents/temp/build
        key: ${{ runner.os }}-20210307
    - name: Setup seed
      env:
        AMIKO_GOOGLE_CLIENT_ID: ${{ secrets.AMIKO_GOOGLE_CLIENT_ID }}
        AMIKO_GOOGLE_CLIENT_SECRET: ${{ secrets.AMIKO_GOOGLE_CLIENT_SECRET }}
        COMED_GOOGLE_CLIENT_ID: ${{ secrets.COMED_GOOGLE_CLIENT_ID }}
        COMED_GOOGLE_CLIENT_SECRET: ${{ secrets.COMED_GOOGLE_CLIENT_SECRET }}
      run: |
        cp seed.in.conf seed.conf
        sed -i.bak -e "s/AMIKO_GOOGLE_CLIENT_ID=''/AMIKO_GOOGLE_CLIENT_ID='$AMIKO_GOOGLE_CLIENT_ID'/g" seed.conf
        sed -i.bak -e "s/AMIKO_GOOGLE_CLIENT_SECRET=''/AMIKO_GOOGLE_CLIENT_SECRET='$AMIKO_GOOGLE_CLIENT_SECRET'/g" seed.conf
        sed -i.bak -e "s/COMED_GOOGLE_CLIENT_ID=''/COMED_GOOGLE_CLIENT_ID='$COMED_GOOGLE_CLIENT_ID'/g" seed.conf
        sed -i.bak -e "s/COMED_GOOGLE_CLIENT_SECRET=''/COMED_GOOGLE_CLIENT_SECRET='$COMED_GOOGLE_CLIENT_SECRET'/g" seed.conf
    - name: Setup step
      run: |
        sed -e "s/#STEP/STEP/g" steps.in.conf > steps.conf
    - name: Install dependencies
      run: |
        sudo apt install libgtk-3-dev libwebkit2gtk-4.0-dev libssl-dev pcscd libpcsclite-dev
    - name: Build
      run: ./build.sh
    - uses: actions/upload-artifact@v2
      with:
        name: Artifact
        path: |
          ~/Documents/temp/build/AmiKo-wx/AmiKo-wx-mk/*.rpm
          ~/Documents/temp/build/AmiKo-wx/AmiKo-wx-mk/*.tar.gz
          ~/Documents/temp/build/AmiKo-wx/AmiKo-wx-mk/*.deb
          ~/Documents/temp/build/AmiKo-wx/AmiKo-wx-mk/*.md5
